sudo: false
language: c
compiler:
  - gcc
  - clang
cache: ccache
env:
    - BUILD="make -j2"
    - BUILD="make -j3"
before_install:
  - df -h
  - mount
before_script:
  - ls -l /tmp
  - ls -l /usr/bin/gcc*
  - env
script:
  - ${BUILD}
# Additional builds in the matrix
matrix:
  include:
    - addons:
        apt:
          sources:
            # PPAs for newer toolchains
            - ubuntu-toolchain-r-test
          packages:
            gcc-5
      language: generic
      compiler: none
      env:
        - COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
        - CFLAGS="-fsanitize=thread -fuse-ld=gold"
        - BUILD="make -j2"
