sudo: false
language: c
compiler:
  - gcc
  - clang
cache: ccache
env:
    - BUILD="make -j2"
    - BUILD="make -j3"
before_install:
  - df -h
before_script:
  - ls -l /tmp
script:
  - ${BUILD}
# Additional builds in the matrix
matrix:
  include:
    - addons:
        apt:
          sources:
            # PPAs for newer toolchains
            - ubuntu-toolchain-r-test
          packages:
            gcc-5
      language: none
      compiler: none
      env:
        - CC=gcc-5
        - BUILD="make -j2"
      before_script:
        - ls -l /usr/bin/gcc-*
        - env
